### ISSUE TITLE
次に作業するあいうえお作文の決定

### ISSUE THREAD

**Issue by kentomiya89** [ayumihashimoto/github_practice#21]
次に作業するあいうえお作文を決めたいのですが、２つあります。

真下くんの案　#12 　
椎橋くんの案   #10

どちらを次に作業するかみんなの意見をお願いします！

真下くん
- [ ] #12 
- [x] #10 

椎橋くん
- [x] #12 
- [ ] #10

谷口くん
- [x] #12 
- [ ] #10

ちなみに僕は　真下くんの案です。

**Comment by shiibashiakira** [comment]
真下くんのに１票

**Comment by kentomiya89** [comment]
２つに分かれましたねー

**Comment by MashimoR** [comment]
俺はどっちでもいいよ！ 🙆‍♂️ 
たださしすせそ #10 の方が楽だと思うよ！

**Comment by a-mochi** [comment]
じゃんけん！

**Comment by shiibashiakira** [comment]
しあわせだよ　　難しそうだったら
さしすせそ　にしたい

**Comment by kentomiya89** [comment]
多数決にしますか？

真下くん　３票
椎橋くん　1票

**Comment by MashimoR** [comment]
ええんか？

**Comment by shiibashiakira** [comment]
ましもくんのにしましょう！

**Comment by kentomiya89** [comment]
僕は大丈夫です！

**Comment by MashimoR** [comment]
谷口くんは？

**Comment by kentomiya89** [comment]
谷口くんはどうですか？

**Comment by KentaroTaniguchi** [comment]
大丈夫です！

**Comment by MashimoR** [comment]
じゃあ #12 で行きましょう

**Comment by kentomiya89** [comment]
では、真下くんの案にしましょう！

**Comment by kentomiya89** [comment]
議題解決しました
閉じます！
